# Generated by Django 5.0.3 on 2024-04-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0002_alter_float_elevator_delete_elevator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='float',
            name='balkon_lodge',
        ),
        migrations.AddField(
            model_name='float',
            name='balkon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='float',
            name='lodge',
            field=models.IntegerField(default=0),
        ),
    ]
