# Generated by Django 5.0.3 on 2024-04-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0003_remove_float_balkon_lodge_float_balkon_float_lodge'),
    ]

    operations = [
        migrations.AddField(
            model_name='float',
            name='credit',
            field=models.BooleanField(default=False),
        ),
    ]
