# Generated by Django 5.0.3 on 2024-04-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0004_float_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('deal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='float',
            name='elevator',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='float',
            name='deal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='float.deal'),
        ),
    ]
