# Generated by Django 5.0.3 on 2024-04-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0005_deal_alter_float_elevator_float_deal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalkonLodge',
        ),
    ]
