# Generated by Django 5.0.3 on 2024-04-25 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0006_delete_balkonlodge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_housing',
            fields=[
                ('type_of_housing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='float',
            name='type_of_housing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='float.type_of_housing'),
        ),
    ]
