# Generated by Django 5.0.3 on 2024-04-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0007_type_of_housing_float_type_of_housing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='float',
            name='ceiling_height',
        ),
        migrations.AddField(
            model_name='float',
            name='lavatory',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
