# Generated by Django 5.0.3 on 2024-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0008_remove_float_ceiling_height_float_lavatory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='float',
            name='balkon',
        ),
        migrations.RemoveField(
            model_name='float',
            name='lodge',
        ),
        migrations.AddField(
            model_name='float',
            name='balkon_lodge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='float',
            name='price2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='cnt_room',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='elevator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='max_floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='total_area',
            field=models.FloatField(null=True),
        ),
    ]
