# Generated by Django 5.0.3 on 2024-04-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0009_remove_float_balkon_remove_float_lodge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='float',
            old_name='balkon_lodge',
            new_name='balkonlodge',
        ),
        migrations.RenameField(
            model_name='float',
            old_name='cnt_room',
            new_name='cntroom',
        ),
        migrations.RenameField(
            model_name='float',
            old_name='living_area',
            new_name='livingarea',
        ),
        migrations.RenameField(
            model_name='float',
            old_name='max_floor',
            new_name='maxfloor',
        ),
        migrations.RenameField(
            model_name='float',
            old_name='total_area',
            new_name='totalarea',
        ),
        migrations.RemoveField(
            model_name='float',
            name='type_of_house',
        ),
        migrations.AddField(
            model_name='float',
            name='typeofhouse',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='deal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='finishing',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='garbage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='gas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='heating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='parking',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='repair',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='type_of_housing',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='float',
            name='window',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
