# Generated by Django 5.0.3 on 2024-04-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0010_rename_balkon_lodge_float_balkonlodge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='float',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
