# Generated by Django 5.0.3 on 2024-04-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0012_float_address_alter_float_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='float',
            old_name='type_of_housing',
            new_name='typeofhousing',
        ),
    ]
