# Generated by Django 5.0.3 on 2024-04-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0013_rename_type_of_housing_float_typeofhousing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='float',
            name='credit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
