# Generated by Django 5.0.3 on 2024-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0015_rename_kitchen_area_float_kitchenarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddresCoord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('width', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.DeleteModel(
            name='Finishing',
        ),
        migrations.DeleteModel(
            name='Garbage',
        ),
        migrations.DeleteModel(
            name='Gas',
        ),
        migrations.DeleteModel(
            name='Heating',
        ),
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
        migrations.DeleteModel(
            name='Repair',
        ),
        migrations.DeleteModel(
            name='Type_of_housing',
        ),
        migrations.DeleteModel(
            name='TypeOfHouse',
        ),
        migrations.DeleteModel(
            name='Window',
        ),
    ]
