# Generated by Django 5.0.3 on 2024-04-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0018_alter_history_user_history_date_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='date',
            new_name='create_date_dttm',
        ),
    ]
