# Generated by Django 5.0.3 on 2024-04-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0020_history_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='link',
            field=models.URLField(max_length=1500, null=True),
        ),
    ]
