# Generated by Django 5.0.3 on 2024-05-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0022_alter_history_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=3000, null=True, unique=True)),
            ],
        ),
    ]
