# Generated by Django 5.0.3 on 2024-05-01 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0023_linkarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='link_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='float.linkarea'),
        ),
    ]
