# Generated by Django 5.0.3 on 2024-05-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0024_history_link_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='link_id',
            new_name='linkid',
        ),
    ]
