# Generated by Django 5.0.3 on 2024-05-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0025_rename_link_id_history_linkid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='linkid',
            new_name='linkarea',
        ),
    ]
